/* File: Mistral2.i, generated by mk_interface.py */
%module Mistral2 

%{
#include <Mistral2.hpp>
#include <iostream>
#include <vector>
#include <mistral_solver.hpp>
#include <mistral_search.hpp>
%}

%include "src/Mistral2.hpp"

%template(Mistral2ExpArray) Mistral2Array< Mistral2_Expression* >;
%template(Mistral2IntArray) Mistral2Array< int >;
%template(Mistral2DoubleArray) Mistral2Array< double >;

