/* File: SatWrapper.i, generated by mk_interface.py */
%module SatWrapper 

%{
#include <SatWrapper.hpp>
#include <vector>
#include <iostream>
#include "Solver.h"
%}

%include "src/SatWrapper.hpp"

%template(SatWrapperExpArray) SatWrapperArray< SatWrapper_Expression* >;
%template(SatWrapperIntArray) SatWrapperArray< int >;
%template(SatWrapperDoubleArray) SatWrapperArray< double >;

