__author__ = 'michael'

SCALING_FACTOR = 1000; #defines how many decimal places of accuracy the solver can handle

RATIO_CALORIES_PROTEIN = 0.2
RATIO_CALORIES_CARBS = 0.6
RATIO_CALORIES_FAT = 0.2
RATIO_CALORIES_SATFAT = 0.11
RATIO_CALORIES_SUGAR = 0.18

SALT_LIMIT_GRAMS = 6
FIBRE_MINIMUM_GRAMS = 18

CALORIES_PER_GRAM_PROTEIN = 4
CALORIES_PER_GRAM_CARBS = 4
CALORIES_PER_GRAM_FAT = 9
CALORIES_PER_GRAM_ALCOHOL = 7

DEFAULT_ERROR_MARGIN = 5

ALLOWED_REQUIREMENTS_RESTRICTIONS = ("<",">","<=",">=")
ALLOWED_INGREDIENT_RESTRICTIONS = ("<",">","<=",">=","=")