/* File: MipWrapper.i, generated by mk_interface.py */
%module MipWrapper 

%{
#include <MipWrapper.hpp>
#include <vector>
#include <stdlib.h>
#include <climits>
%}

%include "src/MipWrapper.hpp"

%template(MipWrapperExpArray) MipWrapperArray< MipWrapper_Expression* >;
%template(MipWrapperIntArray) MipWrapperArray< int >;
%template(MipWrapperDoubleArray) MipWrapperArray< double >;

